In [3]:
import torch
print(torch.__version__)


1.7.1+cu110


In [4]:
import torch.nn as nn


In [5]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(128 , 32) 
        self.layer2 = nn.Linear(32 , 16)
        self.layer3 = nn.Linear(16 , 1)
    
    def forward(self, features):
        # 32, 128
        x = self.layer1(features)
        print(x.shape)
        # 32 , 32
        x = self.layer2(x)
        # 32, 1
        x = self.layer3(x)
        return x
        

In [8]:
model = Model()
features = torch.rand((2,128))
#print(features)
model(features)

torch.Size([2, 32])


tensor([[-0.1807],
        [-0.1742]], grad_fn=<AddmmBackward>)

In [9]:
features.device


device(type='cpu')

In [13]:
features = features.to("cuda")
model =  Model()
model.to("cuda")
model(features)

torch.Size([2, 32])


tensor([[-0.3112],
        [-0.2468]], device='cuda:0', grad_fn=<AddmmBackward>)

In [14]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.base = nn.Sequential(
        nn.Linear(128 , 32),
        nn.Linear(32 , 16),
        nn.Linear(16 , 1)
        ) 
        
    
    def forward(self, features):
        # 32, 128
        x = self.base(features)
        return x

In [15]:
features = features.to("cuda")
model =  Model()
model.to("cuda")
model(features)

tensor([[0.2651],
        [0.2250]], device='cuda:0', grad_fn=<AddmmBackward>)